#!/bin/bash

# Autobuild the Image on Docker Hub with advanced options and buildx for multiarch images
# read more: https://github.com/Tob1asDocker/dockerhubhooksexample

# '--push' shorthand for '--output=type=registry'

set -ex

echo "### RUN build START: using buildx ###"
echo "Image Name: ${IMAGE_NAME} (Repo: ${DOCKER_REPO}, Tag: ${DOCKER_TAG})"
echo "Dockerfile Path/Name: ${DOCKERFILE_PATH}"
BUILDPLATFORM="${BUILDPLATFORM:-"linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"}"
echo "Architectures=${BUILDPLATFORM}"

# for minio (release) only
if [[ ${IMAGE_NAME} == *"minio:git-release"* ]]; then
	RELEASE=$(curl -s https://api.github.com/repos/minio/minio/releases/latest | grep 'tag_name' | cut -d\" -f4)
	echo "MINIO_RELEASE_VERSION=${RELEASE}"
	BUILD_ARG_VERSION="--build-arg MINIO_RELEASE_VERSION=${RELEASE}"
	TAG_VERSION="--tag ${DOCKER_REPO}:${RELEASE}"
else
    BUILD_ARG_VERSION=""
    TAG_VERSION=""
fi

docker buildx build --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --build-arg VCS_REF="$(git rev-parse --short HEAD)" ${BUILD_ARG_VERSION} --tag "${IMAGE_NAME}" ${TAG_VERSION} --platform "${BUILDPLATFORM}" --file "${DOCKERFILE_PATH}" --push .

echo "### RUN build END"
