name: 'build docker images'

on:
  #push:
  #  branches:
  #    - 'main'
  #    - 'master'
  workflow_dispatch:
  schedule:
    - cron: '0 3 */7 * *'  # At 03:00 on every 7th day-of-month.

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shell-Script
        id: script
        run: |
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BUILD_DATE_NUMERIC="${BUILD_DATE//[^[:digit:]]/}"
          COMMIT_HASH=${GITHUB_SHA::8}
          GITHUB_REPO=${GITHUB_REPOSITORY,,}
          GITHUB_REPO_SHORT=${GITHUB_REPO#*/}
          DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/${GITHUB_REPO_SHORT}
          REDHAT_QUAY_REPO=${{ secrets.REDHAT_QUAY_USERNAME }}/${GITHUB_REPO_SHORT}

          # MinIO
          RELEASE=$(curl -s https://api.github.com/repos/minio/minio/releases/latest | grep 'tag_name' | cut -d\" -f4)
          echo "MINIO_RELEASE_VERSION=${RELEASE}"
          MINIO_RELEASE_VERSION=${RELEASE}
          
          # Set output parameters to GitHub action.
          echo ::set-output name=build_date::${BUILD_DATE}
          echo ::set-output name=build_date_numeric::${BUILD_DATE_NUMERIC}
          echo ::set-output name=commit_hash::${COMMIT_HASH}
          echo ::set-output name=github_repo::${GITHUB_REPO}
          echo ::set-output name=docker_repo::${DOCKER_REPO}
          echo ::set-output name=redhat_quay_repo::${REDHAT_QUAY_REPO}
          # MinIO
          echo ::set-output name=minio_release_version::${MINIO_RELEASE_VERSION}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub 
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to RED HAT Quay.io Container Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REDHAT_QUAY_USERNAME }}
          password: ${{ secrets.REDHAT_QUAY_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./alpine.multiarch.release.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          pull: true
          push: true
          build-args: |
            BUILD_DATE=${{steps.script.outputs.build_date}}
            VCS_REF=${{steps.script.outputs.commit_hash}}
            MINIO_RELEASE_VERSION=${{steps.script.outputs.minio_release_version}}
          tags: |
            ghcr.io/${{steps.script.outputs.github_repo}}:${{steps.script.outputs.minio_release_version}}
            ghcr.io/${{steps.script.outputs.github_repo}}:latest
            docker.io/${{steps.script.outputs.docker_repo}}:${{steps.script.outputs.minio_release_version}}
            docker.io/${{steps.script.outputs.docker_repo}}:latest
            quay.io/${{steps.script.outputs.redhat_quay_repo}}:${{steps.script.outputs.minio_release_version}}
            quay.io/${{steps.script.outputs.redhat_quay_repo}}:latest
